### ISSUE TITLE
HardFault with NUCLEO-H723ZG, RTOS disabled

### ISSUE THREAD

**Issue by marcocipriani01** [stm32-hotspot/STM32H7-LwIP-Examples#10]
Hello,
I'm trying to use LwIP on my NUCLEO-H723ZG, replicating all the steps described in the README, except for enabling RTOS (I don't need it right now). Unfortunately, `HardFault_Handler` is being called somewhere during the execution of `MX_LWIP_Init()`, and I can't figure out why. Here's the call stack when the fault occurs:

![image](https://github.com/stm32-hotspot/STM32H7-LwIP-Examples/assets/20319029/b6d91517-dd38-4c2b-97ee-75f23f506cc3)

Just for confirmation, here are all the steps I did:
- Enabled debug, speculation, ICache, DCache and MPU. I followed the STM32H72x memory layout table and set:

![image](https://github.com/stm32-hotspot/STM32H7-LwIP-Examples/assets/20319029/048ab56a-3954-4646-b926-4a169653bc4d)

- Set the correct addresses for Ethernet, and left the "Ethernet global interrupt" disabled since I'm not using RTOS (as stated in #1). Set every ETH pin to "Very high" speed.

![image](https://github.com/stm32-hotspot/STM32H7-LwIP-Examples/assets/20319029/0b88abc8-1354-40a1-b066-d4e1e387218f)

- Set LwIP with static IP, LAN8742 interface, heap pointer to `0x30000200`, and set all the options in the "Key options" and "Checksum" tabs as per instructions in the README.
- Added a call to `MX_LWIP_Process()` in the `main` `while (1)` loop (see #1)
- Updated `STM32H723ZGTX_FLASH.ld` with the changes in the _STM32H723_Nucleo_ETH_ folder (searching for `ETH_CODE`)
- I did **not** follow the steps in the _Modifying the code_ section (or any other change I found searching for `ETH_CODE`) because doing any of that resulted in compilation errors. I presume those changes are required only for using RTOS, correct me if I'm wrong.

Strangely enough, I don't get a `HardFault` if I enable DHCP in CubeMX. However, in that case ethernet doesn't connect and if I try to `printf` the STM32's IP (`gnetif.ip_addr.addr`) I always get `0.0.0.0`.

Any help would be highly appreciated,
Marco

**Comment by marcocipriani01** [comment]
Nevermind, I made a mistake in configuring the MPU. Sorry.

**Comment by tunaayranci** [comment]
![Image](https://github.com/user-attachments/assets/06c82d45-98f2-4b69-b256-9b105d142bf5)
@marcocipriani01  what was the mistake i didn't recognize it.I am getting this error.Do you know why it is happening?
